In [18]:
import numpy as np
import pandas as pd

1.Creating DataFrame

In [ ]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
} # data

df=pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [7]:
# using a list where we dont have any headers
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
columns=["Name","Age","City","Salary"]
df2=pd.DataFrame(data_list,columns=columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

2.Selection and Indexing of columns

In [8]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df["Name"] # agar hame sirf ek column chahiye

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [12]:
# agar hame 2 ya usse jyada column chahiye to hum use karenge list of lists
df[["Name","Age"]]

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

3.Creating a new column

In [48]:
df2["Designation"]=["Doctor","Eng","Doctor","Eng"]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000         Eng
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000         Eng

4.Remove a column

In [38]:
df2.drop("Designation",axis=1) # drop se main data se remove nahi hota hai vo bas copy dikhata hai ki aisa dikhega apka data

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [49]:
# to agar hame main data se bhi hatana hai to hum use karenge inplace=True
df2.drop("Designation",axis=1,inplace=True)

In [50]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [51]:
# delete multiple columns
df2.drop(["City","Salary"],axis=1,inplace=True)

In [52]:
df2

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [53]:
# we can delete a row also just give axis =0
df2.drop(0,axis=0)

    Name  Age
1   Anna   34
2  Peter   29
3  Linda   42

5. Selecting a Row

In [ ]:
# for directly selecting a row we use loc(location)
df2.loc[1]

Name    Anna
Age       34
Name: 1, dtype: object

In [57]:
df2.loc[[1,2]]

    Name  Age
1   Anna   34
2  Peter   29

6.Selecting subsets of rows and columns

In [59]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
} # data

df3=pd.DataFrame(data)
df3

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df3.loc[[0,1]][["City","Salary"]] # if we want to select specific portion

       City  Salary
0  New York   65000
1     Paris   70000

In [61]:
df3.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

7.Conditional Selection

In [66]:
df3

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [68]:
# i only want to see those people whose age is above 30
df3[df3["Age"]>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [72]:
# i onlt want people whose age is above 30 and their city must be paris
df3[(df3["Age"]>30) & (df3["City"]=="Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000